// <auto-generated />
using System;
using BalancerAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BalancerAPI.Migrations
{
    [DbContext(typeof(BalancerDbContext))]
    [Migration("20260322214330_AddCurrentWeekView")]
    partial class AddCurrentWeekView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BalancerAPI.Data.Models.AdjustLogDaily", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("Adjustment")
                        .HasColumnType("integer")
                        .HasColumnName("adjustment");

                    b.HasKey("Uuid");

                    b.ToTable("adjust_log_daily", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.AdjustLogWeekly", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("Apothecary")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary");

                    b.Property<int>("Aquamancer")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer");

                    b.Property<int>("Assassin")
                        .HasColumnType("integer")
                        .HasColumnName("assassin");

                    b.Property<int>("Avenger")
                        .HasColumnType("integer")
                        .HasColumnName("avenger");

                    b.Property<int>("Berserker")
                        .HasColumnType("integer")
                        .HasColumnName("berserker");

                    b.Property<int>("Conjurer")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer");

                    b.Property<int>("Crusader")
                        .HasColumnType("integer")
                        .HasColumnName("crusader");

                    b.Property<int>("Cryomancer")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer");

                    b.Property<int>("Defender")
                        .HasColumnType("integer")
                        .HasColumnName("defender");

                    b.Property<int>("Earthwarden")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden");

                    b.Property<int>("Luminary")
                        .HasColumnType("integer")
                        .HasColumnName("luminary");

                    b.Property<int>("Protector")
                        .HasColumnType("integer")
                        .HasColumnName("protector");

                    b.Property<int>("Pyromancer")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer");

                    b.Property<int>("Revenant")
                        .HasColumnType("integer")
                        .HasColumnName("revenant");

                    b.Property<int>("Sentinel")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel");

                    b.Property<int>("Spiritguard")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard");

                    b.Property<int>("Thunderlord")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord");

                    b.Property<int>("Vindicator")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator");

                    b.HasKey("Uuid");

                    b.ToTable("adjust_log_weekly", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.BaseWeight", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Uuid");

                    b.ToTable("base_weights", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.ExperimentalSpecLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Apothecary")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("apothecary");

                    b.Property<string>("Aquamancer")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("aquamancer");

                    b.Property<string>("Assassin")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("assassin");

                    b.Property<string>("Avenger")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("avenger");

                    b.Property<string>("Berserker")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("berserker");

                    b.Property<string>("Conjurer")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("conjurer");

                    b.Property<string>("Crusader")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("crusader");

                    b.Property<string>("Cryomancer")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("cryomancer");

                    b.Property<string>("Defender")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("defender");

                    b.Property<string>("Earthwarden")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("earthwarden");

                    b.Property<string>("Luminary")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("luminary");

                    b.Property<string>("Protector")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("protector");

                    b.Property<string>("Pyromancer")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("pyromancer");

                    b.Property<string>("Revenant")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("revenant");

                    b.Property<string>("Sentinel")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("sentinel");

                    b.Property<string>("Spiritguard")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("spiritguard");

                    b.Property<string>("Thunderlord")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("thunderlord");

                    b.Property<string>("Vindicator")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("vindicator");

                    b.HasKey("Id");

                    b.ToTable("experimental_spec_logs", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.ExperimentalSpecWeight", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("ApothecaryOffset")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_offset");

                    b.Property<int>("AquamancerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_offset");

                    b.Property<int>("AssassinOffset")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_offset");

                    b.Property<int>("AvengerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_offset");

                    b.Property<int>("BerserkerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_offset");

                    b.Property<int>("ConjurerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_offset");

                    b.Property<int>("CrusaderOffset")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_offset");

                    b.Property<int>("CryomancerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_offset");

                    b.Property<int>("DefenderOffset")
                        .HasColumnType("integer")
                        .HasColumnName("defender_offset");

                    b.Property<int>("EarthwardenOffset")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_offset");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("LuminaryOffset")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_offset");

                    b.Property<int>("ProtectorOffset")
                        .HasColumnType("integer")
                        .HasColumnName("protector_offset");

                    b.Property<int>("PyromancerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_offset");

                    b.Property<int>("RevenantOffset")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_offset");

                    b.Property<int>("SentinelOffset")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_offset");

                    b.Property<int>("SpiritguardOffset")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_offset");

                    b.Property<int>("ThunderlordOffset")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_offset");

                    b.Property<int>("VindicatorOffset")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_offset");

                    b.HasKey("Uuid");

                    b.ToTable("experimental_spec_weights", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.ExperimentalSpecWeightWeekly", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("WeekStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("week_start_date");

                    b.Property<int>("ApothecaryOffset")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_offset");

                    b.Property<int>("AquamancerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_offset");

                    b.Property<int>("AssassinOffset")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_offset");

                    b.Property<int>("AvengerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_offset");

                    b.Property<int>("BerserkerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_offset");

                    b.Property<int>("ConjurerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_offset");

                    b.Property<int>("CrusaderOffset")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_offset");

                    b.Property<int>("CryomancerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_offset");

                    b.Property<int>("DefenderOffset")
                        .HasColumnType("integer")
                        .HasColumnName("defender_offset");

                    b.Property<int>("EarthwardenOffset")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_offset");

                    b.Property<int>("LuminaryOffset")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_offset");

                    b.Property<int>("ProtectorOffset")
                        .HasColumnType("integer")
                        .HasColumnName("protector_offset");

                    b.Property<int>("PyromancerOffset")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_offset");

                    b.Property<int>("RevenantOffset")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_offset");

                    b.Property<int>("SentinelOffset")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_offset");

                    b.Property<int>("SpiritguardOffset")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_offset");

                    b.Property<int>("ThunderlordOffset")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_offset");

                    b.Property<int>("VindicatorOffset")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_offset");

                    b.HasKey("Uuid", "WeekStartDate");

                    b.ToTable("experimental_spec_weights_weekly", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.ExperimentalSpecsWl", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("ApothecaryDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_deaths");

                    b.Property<int>("ApothecaryKills")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_kills");

                    b.Property<int>("ApothecaryLosses")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_losses");

                    b.Property<int>("ApothecaryWins")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_wins");

                    b.Property<int>("AquamancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_deaths");

                    b.Property<int>("AquamancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_kills");

                    b.Property<int>("AquamancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_losses");

                    b.Property<int>("AquamancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_wins");

                    b.Property<int>("AssassinDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_deaths");

                    b.Property<int>("AssassinKills")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_kills");

                    b.Property<int>("AssassinLosses")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_losses");

                    b.Property<int>("AssassinWins")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_wins");

                    b.Property<int>("AvengerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_deaths");

                    b.Property<int>("AvengerKills")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_kills");

                    b.Property<int>("AvengerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_losses");

                    b.Property<int>("AvengerWins")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_wins");

                    b.Property<int>("BerserkerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_deaths");

                    b.Property<int>("BerserkerKills")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_kills");

                    b.Property<int>("BerserkerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_losses");

                    b.Property<int>("BerserkerWins")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_wins");

                    b.Property<int>("ConjurerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_deaths");

                    b.Property<int>("ConjurerKills")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_kills");

                    b.Property<int>("ConjurerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_losses");

                    b.Property<int>("ConjurerWins")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_wins");

                    b.Property<int>("CrusaderDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_deaths");

                    b.Property<int>("CrusaderKills")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_kills");

                    b.Property<int>("CrusaderLosses")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_losses");

                    b.Property<int>("CrusaderWins")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_wins");

                    b.Property<int>("CryomancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_deaths");

                    b.Property<int>("CryomancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_kills");

                    b.Property<int>("CryomancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_losses");

                    b.Property<int>("CryomancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_wins");

                    b.Property<int>("DefenderDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("defender_deaths");

                    b.Property<int>("DefenderKills")
                        .HasColumnType("integer")
                        .HasColumnName("defender_kills");

                    b.Property<int>("DefenderLosses")
                        .HasColumnType("integer")
                        .HasColumnName("defender_losses");

                    b.Property<int>("DefenderWins")
                        .HasColumnType("integer")
                        .HasColumnName("defender_wins");

                    b.Property<int>("EarthwardenDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_deaths");

                    b.Property<int>("EarthwardenKills")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_kills");

                    b.Property<int>("EarthwardenLosses")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_losses");

                    b.Property<int>("EarthwardenWins")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_wins");

                    b.Property<int>("LuminaryDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_deaths");

                    b.Property<int>("LuminaryKills")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_kills");

                    b.Property<int>("LuminaryLosses")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_losses");

                    b.Property<int>("LuminaryWins")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_wins");

                    b.Property<int>("ProtectorDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("protector_deaths");

                    b.Property<int>("ProtectorKills")
                        .HasColumnType("integer")
                        .HasColumnName("protector_kills");

                    b.Property<int>("ProtectorLosses")
                        .HasColumnType("integer")
                        .HasColumnName("protector_losses");

                    b.Property<int>("ProtectorWins")
                        .HasColumnType("integer")
                        .HasColumnName("protector_wins");

                    b.Property<int>("PyromancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_deaths");

                    b.Property<int>("PyromancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_kills");

                    b.Property<int>("PyromancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_losses");

                    b.Property<int>("PyromancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_wins");

                    b.Property<int>("RevenantDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_deaths");

                    b.Property<int>("RevenantKills")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_kills");

                    b.Property<int>("RevenantLosses")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_losses");

                    b.Property<int>("RevenantWins")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_wins");

                    b.Property<int>("SentinelDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_deaths");

                    b.Property<int>("SentinelKills")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_kills");

                    b.Property<int>("SentinelLosses")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_losses");

                    b.Property<int>("SentinelWins")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_wins");

                    b.Property<int>("SpiritguardDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_deaths");

                    b.Property<int>("SpiritguardKills")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_kills");

                    b.Property<int>("SpiritguardLosses")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_losses");

                    b.Property<int>("SpiritguardWins")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_wins");

                    b.Property<int>("ThunderlordDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_deaths");

                    b.Property<int>("ThunderlordKills")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_kills");

                    b.Property<int>("ThunderlordLosses")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_losses");

                    b.Property<int>("ThunderlordWins")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_wins");

                    b.Property<int>("VindicatorDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_deaths");

                    b.Property<int>("VindicatorKills")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_kills");

                    b.Property<int>("VindicatorLosses")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_losses");

                    b.Property<int>("VindicatorWins")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_wins");

                    b.HasKey("Uuid");

                    b.ToTable("experimental_specs_wl", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.ExperimentalSpecsWlCurrentWeek", b =>
                {
                    b.Property<int>("ApothecaryDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_deaths");

                    b.Property<int>("ApothecaryKills")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_kills");

                    b.Property<int>("ApothecaryLosses")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_losses");

                    b.Property<int>("ApothecaryWins")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_wins");

                    b.Property<int>("AquamancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_deaths");

                    b.Property<int>("AquamancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_kills");

                    b.Property<int>("AquamancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_losses");

                    b.Property<int>("AquamancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_wins");

                    b.Property<int>("AssassinDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_deaths");

                    b.Property<int>("AssassinKills")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_kills");

                    b.Property<int>("AssassinLosses")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_losses");

                    b.Property<int>("AssassinWins")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_wins");

                    b.Property<int>("AvengerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_deaths");

                    b.Property<int>("AvengerKills")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_kills");

                    b.Property<int>("AvengerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_losses");

                    b.Property<int>("AvengerWins")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_wins");

                    b.Property<int>("BerserkerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_deaths");

                    b.Property<int>("BerserkerKills")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_kills");

                    b.Property<int>("BerserkerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_losses");

                    b.Property<int>("BerserkerWins")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_wins");

                    b.Property<int>("ConjurerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_deaths");

                    b.Property<int>("ConjurerKills")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_kills");

                    b.Property<int>("ConjurerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_losses");

                    b.Property<int>("ConjurerWins")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_wins");

                    b.Property<int>("CrusaderDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_deaths");

                    b.Property<int>("CrusaderKills")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_kills");

                    b.Property<int>("CrusaderLosses")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_losses");

                    b.Property<int>("CrusaderWins")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_wins");

                    b.Property<int>("CryomancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_deaths");

                    b.Property<int>("CryomancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_kills");

                    b.Property<int>("CryomancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_losses");

                    b.Property<int>("CryomancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_wins");

                    b.Property<int>("DefenderDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("defender_deaths");

                    b.Property<int>("DefenderKills")
                        .HasColumnType("integer")
                        .HasColumnName("defender_kills");

                    b.Property<int>("DefenderLosses")
                        .HasColumnType("integer")
                        .HasColumnName("defender_losses");

                    b.Property<int>("DefenderWins")
                        .HasColumnType("integer")
                        .HasColumnName("defender_wins");

                    b.Property<int>("EarthwardenDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_deaths");

                    b.Property<int>("EarthwardenKills")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_kills");

                    b.Property<int>("EarthwardenLosses")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_losses");

                    b.Property<int>("EarthwardenWins")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_wins");

                    b.Property<int>("LuminaryDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_deaths");

                    b.Property<int>("LuminaryKills")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_kills");

                    b.Property<int>("LuminaryLosses")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_losses");

                    b.Property<int>("LuminaryWins")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_wins");

                    b.Property<int>("ProtectorDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("protector_deaths");

                    b.Property<int>("ProtectorKills")
                        .HasColumnType("integer")
                        .HasColumnName("protector_kills");

                    b.Property<int>("ProtectorLosses")
                        .HasColumnType("integer")
                        .HasColumnName("protector_losses");

                    b.Property<int>("ProtectorWins")
                        .HasColumnType("integer")
                        .HasColumnName("protector_wins");

                    b.Property<int>("PyromancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_deaths");

                    b.Property<int>("PyromancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_kills");

                    b.Property<int>("PyromancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_losses");

                    b.Property<int>("PyromancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_wins");

                    b.Property<int>("RevenantDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_deaths");

                    b.Property<int>("RevenantKills")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_kills");

                    b.Property<int>("RevenantLosses")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_losses");

                    b.Property<int>("RevenantWins")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_wins");

                    b.Property<int>("SentinelDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_deaths");

                    b.Property<int>("SentinelKills")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_kills");

                    b.Property<int>("SentinelLosses")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_losses");

                    b.Property<int>("SentinelWins")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_wins");

                    b.Property<int>("SpiritguardDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_deaths");

                    b.Property<int>("SpiritguardKills")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_kills");

                    b.Property<int>("SpiritguardLosses")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_losses");

                    b.Property<int>("SpiritguardWins")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_wins");

                    b.Property<int>("ThunderlordDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_deaths");

                    b.Property<int>("ThunderlordKills")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_kills");

                    b.Property<int>("ThunderlordLosses")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_losses");

                    b.Property<int>("ThunderlordWins")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_wins");

                    b.Property<string>("Uuid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uuid");

                    b.Property<int>("VindicatorDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_deaths");

                    b.Property<int>("VindicatorKills")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_kills");

                    b.Property<int>("VindicatorLosses")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_losses");

                    b.Property<int>("VindicatorWins")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_wins");

                    b.ToTable((string)null);

                    b.ToView("experimental_specs_wl_current_week", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.ExperimentalSpecsWlDaily", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("DayStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("day_start_date");

                    b.Property<int>("ApothecaryDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_deaths");

                    b.Property<int>("ApothecaryKills")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_kills");

                    b.Property<int>("ApothecaryLosses")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_losses");

                    b.Property<int>("ApothecaryWins")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_wins");

                    b.Property<int>("AquamancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_deaths");

                    b.Property<int>("AquamancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_kills");

                    b.Property<int>("AquamancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_losses");

                    b.Property<int>("AquamancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_wins");

                    b.Property<int>("AssassinDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_deaths");

                    b.Property<int>("AssassinKills")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_kills");

                    b.Property<int>("AssassinLosses")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_losses");

                    b.Property<int>("AssassinWins")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_wins");

                    b.Property<int>("AvengerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_deaths");

                    b.Property<int>("AvengerKills")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_kills");

                    b.Property<int>("AvengerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_losses");

                    b.Property<int>("AvengerWins")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_wins");

                    b.Property<int>("BerserkerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_deaths");

                    b.Property<int>("BerserkerKills")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_kills");

                    b.Property<int>("BerserkerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_losses");

                    b.Property<int>("BerserkerWins")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_wins");

                    b.Property<int>("ConjurerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_deaths");

                    b.Property<int>("ConjurerKills")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_kills");

                    b.Property<int>("ConjurerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_losses");

                    b.Property<int>("ConjurerWins")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_wins");

                    b.Property<int>("CrusaderDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_deaths");

                    b.Property<int>("CrusaderKills")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_kills");

                    b.Property<int>("CrusaderLosses")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_losses");

                    b.Property<int>("CrusaderWins")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_wins");

                    b.Property<int>("CryomancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_deaths");

                    b.Property<int>("CryomancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_kills");

                    b.Property<int>("CryomancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_losses");

                    b.Property<int>("CryomancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_wins");

                    b.Property<int>("DefenderDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("defender_deaths");

                    b.Property<int>("DefenderKills")
                        .HasColumnType("integer")
                        .HasColumnName("defender_kills");

                    b.Property<int>("DefenderLosses")
                        .HasColumnType("integer")
                        .HasColumnName("defender_losses");

                    b.Property<int>("DefenderWins")
                        .HasColumnType("integer")
                        .HasColumnName("defender_wins");

                    b.Property<int>("EarthwardenDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_deaths");

                    b.Property<int>("EarthwardenKills")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_kills");

                    b.Property<int>("EarthwardenLosses")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_losses");

                    b.Property<int>("EarthwardenWins")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_wins");

                    b.Property<int>("LuminaryDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_deaths");

                    b.Property<int>("LuminaryKills")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_kills");

                    b.Property<int>("LuminaryLosses")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_losses");

                    b.Property<int>("LuminaryWins")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_wins");

                    b.Property<int>("ProtectorDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("protector_deaths");

                    b.Property<int>("ProtectorKills")
                        .HasColumnType("integer")
                        .HasColumnName("protector_kills");

                    b.Property<int>("ProtectorLosses")
                        .HasColumnType("integer")
                        .HasColumnName("protector_losses");

                    b.Property<int>("ProtectorWins")
                        .HasColumnType("integer")
                        .HasColumnName("protector_wins");

                    b.Property<int>("PyromancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_deaths");

                    b.Property<int>("PyromancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_kills");

                    b.Property<int>("PyromancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_losses");

                    b.Property<int>("PyromancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_wins");

                    b.Property<int>("RevenantDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_deaths");

                    b.Property<int>("RevenantKills")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_kills");

                    b.Property<int>("RevenantLosses")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_losses");

                    b.Property<int>("RevenantWins")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_wins");

                    b.Property<int>("SentinelDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_deaths");

                    b.Property<int>("SentinelKills")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_kills");

                    b.Property<int>("SentinelLosses")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_losses");

                    b.Property<int>("SentinelWins")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_wins");

                    b.Property<int>("SpiritguardDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_deaths");

                    b.Property<int>("SpiritguardKills")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_kills");

                    b.Property<int>("SpiritguardLosses")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_losses");

                    b.Property<int>("SpiritguardWins")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_wins");

                    b.Property<int>("ThunderlordDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_deaths");

                    b.Property<int>("ThunderlordKills")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_kills");

                    b.Property<int>("ThunderlordLosses")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_losses");

                    b.Property<int>("ThunderlordWins")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_wins");

                    b.Property<int>("VindicatorDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_deaths");

                    b.Property<int>("VindicatorKills")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_kills");

                    b.Property<int>("VindicatorLosses")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_losses");

                    b.Property<int>("VindicatorWins")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_wins");

                    b.HasKey("Uuid", "DayStartDate");

                    b.ToTable("experimental_specs_wl_daily", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.ExperimentalSpecsWlWeekly", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<int>("WeekStartDate")
                        .HasColumnType("integer")
                        .HasColumnName("week_start_date");

                    b.Property<int>("ApothecaryDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_deaths");

                    b.Property<int>("ApothecaryKills")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_kills");

                    b.Property<int>("ApothecaryLosses")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_losses");

                    b.Property<int>("ApothecaryWins")
                        .HasColumnType("integer")
                        .HasColumnName("apothecary_wins");

                    b.Property<int>("AquamancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_deaths");

                    b.Property<int>("AquamancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_kills");

                    b.Property<int>("AquamancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_losses");

                    b.Property<int>("AquamancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("aquamancer_wins");

                    b.Property<int>("AssassinDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_deaths");

                    b.Property<int>("AssassinKills")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_kills");

                    b.Property<int>("AssassinLosses")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_losses");

                    b.Property<int>("AssassinWins")
                        .HasColumnType("integer")
                        .HasColumnName("assassin_wins");

                    b.Property<int>("AvengerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_deaths");

                    b.Property<int>("AvengerKills")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_kills");

                    b.Property<int>("AvengerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_losses");

                    b.Property<int>("AvengerWins")
                        .HasColumnType("integer")
                        .HasColumnName("avenger_wins");

                    b.Property<int>("BerserkerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_deaths");

                    b.Property<int>("BerserkerKills")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_kills");

                    b.Property<int>("BerserkerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_losses");

                    b.Property<int>("BerserkerWins")
                        .HasColumnType("integer")
                        .HasColumnName("berserker_wins");

                    b.Property<int>("ConjurerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_deaths");

                    b.Property<int>("ConjurerKills")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_kills");

                    b.Property<int>("ConjurerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_losses");

                    b.Property<int>("ConjurerWins")
                        .HasColumnType("integer")
                        .HasColumnName("conjurer_wins");

                    b.Property<int>("CrusaderDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_deaths");

                    b.Property<int>("CrusaderKills")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_kills");

                    b.Property<int>("CrusaderLosses")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_losses");

                    b.Property<int>("CrusaderWins")
                        .HasColumnType("integer")
                        .HasColumnName("crusader_wins");

                    b.Property<int>("CryomancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_deaths");

                    b.Property<int>("CryomancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_kills");

                    b.Property<int>("CryomancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_losses");

                    b.Property<int>("CryomancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("cryomancer_wins");

                    b.Property<int>("DefenderDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("defender_deaths");

                    b.Property<int>("DefenderKills")
                        .HasColumnType("integer")
                        .HasColumnName("defender_kills");

                    b.Property<int>("DefenderLosses")
                        .HasColumnType("integer")
                        .HasColumnName("defender_losses");

                    b.Property<int>("DefenderWins")
                        .HasColumnType("integer")
                        .HasColumnName("defender_wins");

                    b.Property<int>("EarthwardenDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_deaths");

                    b.Property<int>("EarthwardenKills")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_kills");

                    b.Property<int>("EarthwardenLosses")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_losses");

                    b.Property<int>("EarthwardenWins")
                        .HasColumnType("integer")
                        .HasColumnName("earthwarden_wins");

                    b.Property<int>("LuminaryDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_deaths");

                    b.Property<int>("LuminaryKills")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_kills");

                    b.Property<int>("LuminaryLosses")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_losses");

                    b.Property<int>("LuminaryWins")
                        .HasColumnType("integer")
                        .HasColumnName("luminary_wins");

                    b.Property<int>("ProtectorDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("protector_deaths");

                    b.Property<int>("ProtectorKills")
                        .HasColumnType("integer")
                        .HasColumnName("protector_kills");

                    b.Property<int>("ProtectorLosses")
                        .HasColumnType("integer")
                        .HasColumnName("protector_losses");

                    b.Property<int>("ProtectorWins")
                        .HasColumnType("integer")
                        .HasColumnName("protector_wins");

                    b.Property<int>("PyromancerDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_deaths");

                    b.Property<int>("PyromancerKills")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_kills");

                    b.Property<int>("PyromancerLosses")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_losses");

                    b.Property<int>("PyromancerWins")
                        .HasColumnType("integer")
                        .HasColumnName("pyromancer_wins");

                    b.Property<int>("RevenantDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_deaths");

                    b.Property<int>("RevenantKills")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_kills");

                    b.Property<int>("RevenantLosses")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_losses");

                    b.Property<int>("RevenantWins")
                        .HasColumnType("integer")
                        .HasColumnName("revenant_wins");

                    b.Property<int>("SentinelDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_deaths");

                    b.Property<int>("SentinelKills")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_kills");

                    b.Property<int>("SentinelLosses")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_losses");

                    b.Property<int>("SentinelWins")
                        .HasColumnType("integer")
                        .HasColumnName("sentinel_wins");

                    b.Property<int>("SpiritguardDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_deaths");

                    b.Property<int>("SpiritguardKills")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_kills");

                    b.Property<int>("SpiritguardLosses")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_losses");

                    b.Property<int>("SpiritguardWins")
                        .HasColumnType("integer")
                        .HasColumnName("spiritguard_wins");

                    b.Property<int>("ThunderlordDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_deaths");

                    b.Property<int>("ThunderlordKills")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_kills");

                    b.Property<int>("ThunderlordLosses")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_losses");

                    b.Property<int>("ThunderlordWins")
                        .HasColumnType("integer")
                        .HasColumnName("thunderlord_wins");

                    b.Property<int>("VindicatorDeaths")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_deaths");

                    b.Property<int>("VindicatorKills")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_kills");

                    b.Property<int>("VindicatorLosses")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_losses");

                    b.Property<int>("VindicatorWins")
                        .HasColumnType("integer")
                        .HasColumnName("vindicator_wins");

                    b.HasKey("Uuid", "WeekStartDate");

                    b.ToTable("experimental_specs_wl_weekly", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.PlayerName", b =>
                {
                    b.Property<string>("Uuid")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.HasKey("Uuid");

                    b.ToTable("names", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.TimeDay", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("time_day", (string)null);
                });

            modelBuilder.Entity("BalancerAPI.Data.Models.TimeWeek", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.ToTable("time_week", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
